version: '3.9'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: beauty-salon-frontend
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production
      PORT: 3000
    restart: unless-stopped
